# Generated by Django 4.1.2 on 2022-10-30 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('is_designer', models.BooleanField(default=True, null=True)),
                ('enrollment_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'evaluation',
                'verbose_name_plural': 'evaluations',
            },
        ),
        migrations.CreateModel(
            name='interview_panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('enrollment_number_1', models.ManyToManyField(related_name='first', to=settings.AUTH_USER_MODEL)),
                ('enrollment_number_2', models.ManyToManyField(related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group_info',
                'verbose_name_plural': 'group_infos',
            },
        ),
        migrations.CreateModel(
            name='Participants_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=50)),
                ('mode_of_entry', models.PositiveSmallIntegerField(choices=[(1, 'recruitment Test'), (2, 'WInter Assingment')], default=1)),
                ('phone_number', models.BigIntegerField(default=123456789, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, null='True', verbose_name='email')),
            ],
            options={
                'verbose_name': 'Participants_detail',
                'verbose_name_plural': 'Participants_details',
            },
        ),
        migrations.CreateModel(
            name='recruitment_season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveIntegerField(choices=[(1, 'development'), (2, 'design')], default=1)),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2022)),
            ],
            options={
                'verbose_name': 'recruitment_season',
                'verbose_name_plural': 'recruitment_seasons',
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_section', models.CharField(max_length=50, unique=True, verbose_name='name of the section')),
                ('total_number_of_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('round_number', models.CharField(max_length=50)),
                ('recruitment_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='winter_assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField()),
                ('evaluation_result', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=500)),
                ('total_marks', models.IntegerField()),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail')),
                ('recruitment_season_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season')),
            ],
            options={
                'verbose_name': 'winter_assingment',
                'verbose_name_plural': 'winter_assingments',
            },
        ),
        migrations.CreateModel(
            name='section_wise_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.CharField(max_length=50)),
                ('marks_in_the_section', models.IntegerField()),
                ('evaluation_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evaluation')),
                ('section_name', models.ForeignKey(db_column='name_of_the_section', on_delete=django.db.models.deletion.CASCADE, to='api.section', to_field='name_of_the_section')),
            ],
            options={
                'verbose_name': 'section_wise_mark',
                'verbose_name_plural': 'section_wise_marks',
            },
        ),
        migrations.CreateModel(
            name='recruitment_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_status', models.PositiveSmallIntegerField(choices=[(1, 'verified'), (2, 'in progress'), (3, 'pending')], default=3)),
                ('evaluation_result', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=500)),
                ('total_marks', models.IntegerField()),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail')),
                ('recruitment_season_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season')),
            ],
            options={
                'verbose_name': 'recruitment_test',
                'verbose_name_plural': 'recruitment_tests',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('answer_text', models.CharField(max_length=500)),
                ('maximum_marks', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section', verbose_name='section of that question')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='interview_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('scheduling_status', models.PositiveSmallIntegerField(choices=[(1, 'scheduled'), (2, 'not answered'), (3, 'pending')], default=3)),
                ('remarks', models.CharField(max_length=500)),
                ('round_number', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail', verbose_name='enrollment_number')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interview_panels', verbose_name='interview panel')),
                ('recruitment_season_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season')),
            ],
            options={
                'verbose_name': 'interview_section',
                'verbose_name_plural': 'interview_sections',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='Question_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='enrollment_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail', verbose_name='enroll. number'),
        ),
        migrations.CreateModel(
            name='connection_question_assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions')),
            ],
        ),
        migrations.CreateModel(
            name='connection_participant_seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participants_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail')),
                ('recruitment_season_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season')),
            ],
        ),
    ]
