# Generated by Django 4.1.2 on 2022-12-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_detail',
            name='id',
        ),

        migrations.AlterField(
            model_name='participants_detail',
            name='enrollment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='connection_participant_seasons',
        ),
    ]
