# Generated by Django 4.1.2 on 2022-12-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_participants_detail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants_detail',
            name='recruitment_season_code',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season'),
        ),
    ]
