# Generated by Django 4.1.2 on 2022-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participants_detail_recruitment_season_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants_detail',
            name='recruitment_season_code',
        ),
        migrations.AddField(
            model_name='participants_detail',
            name='recruitment_season_code',
            field=models.ManyToManyField(to='api.recruitment_season'),
        ),
    ]
