# Generated by Django 4.1.2 on 2022-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_participants_detail_recruitment_season_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants_detail',
            name='Project_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='participants_detail',
            name='mode_of_entry',
            field=models.PositiveSmallIntegerField(choices=[(1, 'recruitment Test'), (2, 'Winter Assingment')], default=1),
        ),
        migrations.AlterField(
            model_name='recruitment_test',
            name='evaluation_result',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment_test',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment_test',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='evaluation_result',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
