# Generated by Django 4.1.2 on 2022-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participants_detail_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants_detail',
            name='Project_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
