# Generated by Django 4.1.2 on 2022-12-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_recruitment_test_evaluation_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_test',
            name='enrollment_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail', unique=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='evaluation_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
