# Generated by Django 4.1.2 on 2022-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_recruitment_test_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winter_assingment',
            name='enrollment_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.participants_detail'),
        ),
    ]
