# Generated by Django 4.1.2 on 2022-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_winter_assingment_evaluation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_test',
            name='recruitment_season_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='recruitment_season_code',
            field=models.IntegerField(),
        ),
    ]
