# Generated by Django 4.1.2 on 2022-12-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_recruitment_test_recruitment_season_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_test',
            name='recruitment_season_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season'),
        ),
        migrations.AlterField(
            model_name='winter_assingment',
            name='recruitment_season_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment_season'),
        ),
    ]
