# Generated by Django 4.1.2 on 2022-12-15 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_connection_question_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='assignee_enrollment_number',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
